name: cicd

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      # - name: Check package Pubspec
      #   id: pubspec
      #   run: |
      #     set +e
      #     git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '${{ matrix.package }}/pubspec.yaml' &> /dev/null
      #     echo ::set-output name=changed::$?
      #     set -e

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: cedx/setup-dart@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
        if: steps.pubspec.outputs.changed == 0
      - run: npm install -g "@semantic-release/changelog"
      - run: npm install -g "@semantic-release/git"
      - run: npm install -g "semantic-release-dart"

      - name: Bump version
        # if: steps.pubspec.outputs.changed == 0
        run: |
          export NODE_PATH="$(npm root -g)"
          npx semantic-release@17
          ls -lah
          git status
          cat pubspec.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to pub
        run: dart pub publish --dry-run

      - uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        # if: steps.pubspec.outputs.changed == 0
        with:
          package_directory: ${{ matrix.package }}
          credential: ${{ secrets.PUB_CREDENTIALS }}
          flutter_package: true
          skip_test: true
